[package]
name = "diffsitter"
version = "0.1.0"
authors = ["Afnan Enayet <afnan@afnan.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.16.1"
structopt = "0.3"
anyhow = "1.0"
phf = { version = "0.8", features = ["macros"] }
colour = "0.5"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
phf = { version = "0.8", features = ["macros"] }

[profile.release]
codegen-units = 1
lto = "thin"
