name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install clang
      run: sudo apt-get install clang
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      run: cargo build --verbose
      env:
        CC: clang
        CXX: clang++
    - name: Run tests
      run: cargo test --verbose
      env:
        CC: clang
        CXX: clang++
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
